#!/usr/bin/env bash

set -e

CONFIG='install.conf.yaml'
DOTBOT_DIR='dotbot'

DOTBOT_BIN='bin/dotbot'
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${CONFIG}" "$@"
